import type { Language } from "@/i18n";

const WORDS = {
  ko: {
    adjectives: [
      "고요한",
      "깊은",
      "잔잔한",
      "따뜻한",
      "맑은",
      "은은한",
      "부드러운",
      "푸른",
      "밝은",
      "조용한",
      "그윽한",
      "투명한",
      "싱그러운",
      "아련한",
      "포근한",
      "서늘한",
      "고운",
      "가벼운",
      "은빛",
      "황금빛",
    ],
    nouns: [
      "새벽",
      "물결",
      "바람",
      "달빛",
      "노을",
      "안개",
      "여명",
      "이슬",
      "강물",
      "숲길",
      "별빛",
      "꽃잎",
      "구름",
      "파도",
      "호수",
      "산들바람",
      "초원",
      "하늘",
      "메아리",
      "여울",
    ],
  },
  en: {
    adjectives: [
      "silent",
      "gentle",
      "deep",
      "warm",
      "clear",
      "soft",
      "bright",
      "quiet",
      "calm",
      "still",
      "misty",
      "golden",
      "silver",
      "tender",
      "distant",
      "faint",
      "serene",
      "vivid",
      "subtle",
      "hushed",
    ],
    nouns: [
      "dawn",
      "ripple",
      "breeze",
      "moonlight",
      "dusk",
      "mist",
      "twilight",
      "dew",
      "stream",
      "meadow",
      "starlight",
      "petal",
      "cloud",
      "tide",
      "lake",
      "glow",
      "echo",
      "shore",
      "rain",
      "horizon",
    ],
  },
} as const;

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function generateTitle(language: Language): string {
  const { adjectives, nouns } = WORDS[language];
  return `${pick(adjectives)} ${pick(nouns)}`;
}
